### ISSUE TITLE
Filtering by language uses sub-string instead of exact matching

### ISSUE THREAD

**Issue by In1quity** [nyurik/dibabel-js#11]
Try to choose Russian language :)
![image](https://user-images.githubusercontent.com/22780294/90305523-6c4e8000-decc-11ea-92f5-7d5a965e26ec.png)

**Comment by nyurik** [comment]
Are you refering to it showig both `ru` and `roa-rup` ?  If so, this is an upstream bug that I already fixed, and hopefully will get merged soon. See https://github.com/elastic/eui/pull/3922

**Comment by In1quity** [comment]
It is cool, then we are waiting for the merge :)

**Comment by nyurik** [comment]
As a temporary workaround, use `lang=ru` instead of `lang:ru`.  Multiple values are supported, e.g. `lang=(ru or fr)`

**Comment by nyurik** [comment]
I fixed this in the upstream (to support `lang=ru` in addition to `lang:ru`), and applied.  The filtering in the combo-box now does proper sub-string searching, so when you type `russ`, it will show all relevant entries:
![image](https://user-images.githubusercontent.com/1641515/93154649-26a2f400-f6d2-11ea-9191-a00d64a80044.png)
