### ISSUE TITLE
Add functionality to add a new template to a local project

### ISSUE THREAD

**Issue by In1quity** [nyurik/dibabel-js#9]
![image](https://user-images.githubusercontent.com/22780294/90305392-d9f9ac80-deca-11ea-9a94-589737ada7e7.png)

**Comment by nyurik** [comment]
Done -- new button in the upper right corner:

![image](https://user-images.githubusercontent.com/1641515/93154703-4afed080-f6d2-11ea-8ea4-fb6c7a02edb3.png)
